export const EDUCATION_QUALIFICATIONS = [
  'SSC / Class 10',
  'HSC / Class 12',
  'Diploma',
  'ITI',
  'Bachelor of Arts (BA)',
  'Bachelor of Science (BSc)',
  'Bachelor of Commerce (BCom)',
  'Bachelor of Computer Applications (BCA)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Engineering (BE)',
  'Bachelor of Technology (BTech)',
  "Other bachelor's degree",
  'Master of Arts (MA)',
  'Master of Science (MSc)',
  'Master of Commerce (MCom)',
  'Master of Computer Applications (MCA)',
  'Master of Business Administration (MBA)',
  'Master of Engineering (ME)',
  'Master of Technology (MTech)',
  "Other master's degree",
  'PhD / Doctorate',
  'Other / Not listed'
]
